### ISSUE TITLE
What environment do you use?

### ISSUE THREAD

**Issue by ankitvad** [kalterfive/dotfiles#1]
What is the env. you are using here on top of Arch Linux ? Is it XFCE ? or X ?

**Comment by kalterfive** [comment]
[i3](https://i3wm.org/)... This is windows manager for X.

**Comment by ankitvad** [comment]
Ahh. nice. I tried setting up i3 on X11, failed. Everything unresponsive on the chromebook. Will try using Arch once, debian caused issues.

**Comment by kalterfive** [comment]
i3 must be run on any Linux or BSD. Moreover, [there are](http://i3wm.org/downloads/) packages for most popular OS.

> I tried setting up i3 on X11, failed.

How starts up WM?

**Comment by ankitvad** [comment]
i tried primarily on the chrome os. was busted there.
