### ISSUE TITLE
would love to display your xpm powered bar

### ISSUE THREAD

**Issue by tukoz** [kalterfive/dotfiles#2]
Hi,
Interesting setup.
I temporary moved my i3 config, cloned yours and moved it all to ~/.config/i3. Then opened your config in a VT to get your key bindings. Got dmenu and TERM working and that's it, eg. not the bar. Could it be because I'm running `i3-gaps` on my Arch box?

**Comment by kalterfive** [comment]
Hello,
I no longer work in i3, so that such problems can occasionally occur. I just don't know about them =)

So. I don't know why, but the `tray_output` is stopping the run panel. Remove it from config.

**Comment by tukoz** [comment]
Thank you for answering.
`tray_output` was already commented. I chmoded `+x` bar.sh which didn't help showing a bit of the panel. I forgot to specify i3-wm version is 4.12 and that there's no warning when loading the config. Might well be a compatibility shift between with i3 newer versions.
